---
title: "Visualization Tests"
author: "Jordan Robinson"
date: "3/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Purpose

Showing visualization examples that can be pulled from data.

```{r}
library(stormwindmodel)
library(tidyverse)
library(ggplot2)
library(sf)
```


Use functions to pull storm data. In this case, winds
```{r, echo = FALSE, include = FALSE}

```

New Plot - take all points at a specific time and plot
#grid from data, then set grid
```{r}

storm_data <- floyd_tracks
grid_data <- county_points
arrow_color <- c("vmax_sust")
arrow_direction <- c("surface_wind_direction")
arrow_radius <- 20
data_date <- c("1999-09-16 05:00:00")
example_state <- c("NC")
graph_title <- c("Max Sustained Winds and Direction at")
legend_title <- c('Max Sustained Winds in m/s')

#Start of code
wind_map_data <- calc_grid_winds(storm_data)
wind_max_sust <- wind_map_data[[arrow_color]]
wind_surface_dir <- wind_map_data[[arrow_direction]]
wind_surface_dir_specific <- wind_surface_dir[data_date,]
wind_max_sust_specific <- wind_max_sust[data_date,]

county_data <- tigris:::counties(state = example_state, cb = T, class = "sf")

storm_center <- create_full_track(storm_data)
storm_center <- storm_center[as.character(storm_center$date) == data_date,]

wind_summary <- data.frame(wind_max_sust_specific, wind_surface_dir_specific)
grid_data_sum <- grid_data[grid_data$gridid %in% rownames(wind_summary),]
practice <- right_join(rownames_to_column(wind_summary), grid_data_sum, 
                       by = c("rowname" ="gridid"))

practice <- practice[practice$rowname %in% county_data$GEOID,]
sf_plot <- sf:::st_as_sf(practice, coords = c("glon", "glat")) %>% 
   sf:::st_set_crs(4269)

#merge counties w/ fibs
ggplot() + 
  geom_sf(data = county_data, color = "black", fill = "lightgray") +
  geom_sf(data = sf_plot)+
  geom_spoke(data = practice, aes(x = glon, y = glat,
                                     angle = wind_surface_dir_specific* pi / 180,
                                     color = wind_max_sust_specific,
                                     radius = wind_max_sust_specific/arrow_radius
                                     ),
               arrow = arrow(length = unit(.075, 'inches')),
               show.legend = TRUE)+
  scale_color_gradient(low='darkblue', high='red')+
  geom_point(data = storm_center, aes(x = tclon, y = tclat, size = 2), 
             color = "orange")+
  labs(x = "Longitude", y = "Latitude", size = "Storm Center",
       color=paste0(legend_title))+
  ggtitle(paste0(graph_title), paste0(data_date))
  
```

#using st_make_object to set grid first
```{r}
arrow_radius <- 0.25

arrow_direction <- c("surface_wind_direction")

arrow_color <- c("vmax_sust")

storm_data <- floyd_tracks

example_state <- c("NC")

example_counties <- c("Columbus", "Brunswick", "New Hanover", "Pender", "Bladen",
                      "Robeson", "Carteret", "Onslow", "Scotland")

example_time <- "1999-09-16 05:00:00"

graph_title <- c("Max Sustained Winds and Direction at")

legend_title <- c('Max Sustained Winds in m/s')

county_data <- list()
#Start of Code
for(i in 1:length(example_state)){
vec <- tigris:::tracts(state = example_state[i], county = example_counties,
                               cb = T, class = "sf")
 county_data[[i]] <- vec 
}

county_data <- do.call(rbind, county_data)

grid_test <- sf::st_make_grid(county_data, square = FALSE, what = "polygons", 
                         cellsize = 0.1)%>% 
  st_sf() %>% 
  mutate(gridid = as.character(1:n()))

data_test <- sf::st_centroid(grid_test)

data_test2 <- data_test%>% 
  mutate(glon = unlist(map(.$geometry, 1)),
         glat = unlist(map(.$geometry, 2))) %>% 
  st_drop_geometry() %>%
  mutate(gridid = gridid,
         glandsea = mapply(check_over_land, tclat = .$glat, tclon = .$glon)) %>% 
  select(gridid, glat, glon, glandsea)


data_test <- data_test %>% 
  left_join(data_test2, by = "gridid")

grid_points <- grid_test[county_data,]
data_test <- data_test[data_test$gridid %in% grid_points$gridid,]

example_winds <- calc_grid_winds(storm_data, data_test)

example_max_sust <- example_winds[[arrow_color]]
example_surface_dir <- example_winds[[arrow_direction]]
example_surface_dir_specific <- example_surface_dir[example_time,]
example_max_sust_specific <- example_max_sust[example_time,]

wind_summary_example <- data.frame(example_max_sust_specific,
                                   example_surface_dir_specific)

example_plot <- right_join(rownames_to_column(wind_summary_example),
                           data_test, by = c("rowname" ="gridid"))


practice <- right_join(grid_points, example_plot, by = c("gridid" = "rowname"))


storm_center <- create_full_track(storm_data)
storm_center <- storm_center[as.character(storm_center$date) == example_time,]

# ggplot()+
#    geom_sf(data = grid_points, fill = "tan", alpha = 0.5)+
#    geom_sf(data = data_test, color = "blue", alpha = 0.5)+
  # geom_sf(data = county_data, fill = NA, color = "black")+
 # geom_point(data = grid_to_model, aes(x= glon, y=glat))


 ggplot()+
  geom_sf(data = practice,
          aes(fill = example_max_sust_specific),
          color = NA)+
  geom_sf(data = county_data, fill = NA, color = "lightgrey", alpha  = 0.3)+
  
  geom_spoke(data = practice, aes(x = glon, y = glat,
                                 angle = example_surface_dir_specific* pi / 180,
                                 color = example_max_sust_specific,
                                 radius = arrow_radius
                                     ), #color = "slateblue",
               arrow = arrow(length = unit(.075, 'inches')),
               show.legend = FALSE)+
  scale_fill_gradient(low='darkblue', high='red')+
  scale_color_gradient(low = 'slateblue', high = 'tomato')+
  ggtitle(paste0(graph_title), paste0(example_time))+
  labs(x= "Longitude", y= "Latitude", fill=paste0(legend_title))+
  geom_point(data = storm_center, aes(x = tclon, y = tclat), color = "orange",
             size = 3)
 

```
