# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

degrees_to_radiansC <- function(degrees) {
    .Call('_stormwindmodel_degrees_to_radiansC', PACKAGE = 'stormwindmodel', degrees)
}

radians_to_degreesC <- function(radians) {
    .Call('_stormwindmodel_radians_to_degreesC', PACKAGE = 'stormwindmodel', radians)
}

